# Generated by Django 5.2.4 on 2025-08-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('usia', models.IntegerField()),
                ('tanggal_periksa', models.DateField()),
                ('jenis_kelamin', models.CharField(max_length=20)),
                ('tinggi_badan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('berat_badan', models.DecimalField(decimal_places=2, max_digits=5)),
                ('riwayat_penyakit', models.TextField(blank=True)),
            ],
        ),
    ]
