# Generated by Django 5.2.4 on 2025-08-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_pasien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasien',
            name='usia',
        ),
    ]
