# Generated by Django 5.2.13 on 2026-05-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0004_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audiofile",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="pasien",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Pasien"},
        ),
        migrations.AddField(
            model_name="audiofile",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audiofile",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pasien",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pasien",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pasien",
            name="jenis_kelamin",
            field=models.CharField(
                choices=[("L", "Laki-laki"), ("P", "Perempuan")], max_length=20
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
